# Generated by Django 2.2.5 on 2022-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingDetails', '0002_auto_20220415_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackers',
            name='forKey',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
