# Generated by Django 2.2.5 on 2022-04-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
    ]
