# Generated by Django 2.2.5 on 2022-04-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.CharField(default='EMP0001', max_length=7)),
                ('empFirstName', models.CharField(default='First Name', max_length=50)),
                ('empLastName', models.CharField(blank=True, default='Last Name', max_length=50)),
                ('empUserName', models.CharField(default='shibint85@gmail.com', max_length=100)),
                ('empAge', models.IntegerField(blank=True, default=0)),
                ('empDOB', models.DateTimeField(auto_now_add=True)),
                ('empGender', models.CharField(blank=True, default='M', max_length=1)),
                ('empAddress', models.CharField(blank=True, default='address', max_length=1000)),
                ('empPhone', models.CharField(blank=True, default='0000000000', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
